/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TR_LDKM;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class Buat_Akun extends javax.swing.JFrame {

    DBConnection konn = new DBConnection();
    Connection koneksi = konn.getConn();
    
    public Buat_Akun() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPPassword = new javax.swing.JPasswordField();
        jPConfir = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jBDaftar = new javax.swing.JButton();
        jBBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(350, 200));
        setMinimumSize(new java.awt.Dimension(350, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buat Akun");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 25));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 100, 29));

        jTUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(jTUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 198, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 29));
        getContentPane().add(jPPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 198, -1));
        getContentPane().add(jPConfir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 198, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Konfmasi ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, 29));

        jBDaftar.setBackground(new java.awt.Color(255, 255, 255));
        jBDaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Add.png"))); // NOI18N
        jBDaftar.setText("  Daftar");
        jBDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDaftarActionPerformed(evt);
            }
        });
        getContentPane().add(jBDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 100, 30));

        jBBack.setBackground(new java.awt.Color(255, 255, 255));
        jBBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/BackK.png"))); // NOI18N
        jBBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBackActionPerformed(evt);
            }
        });
        getContentPane().add(jBBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 40, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/BuatAkun.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTUsernameActionPerformed

    private void jBBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBackActionPerformed
        Login_Admin pindah = new Login_Admin();
        pindah.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBBackActionPerformed

    private void jBDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDaftarActionPerformed
        if (jTUsername.getText().trim().equals("")
                || jPPassword.getText().trim().equals("")
                || jPConfir.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data Tidak Lengkap", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
        } else if (!(jPPassword.getText().equals(jPConfir.getText()))){
            JOptionPane.showMessageDialog(null, "Password tidak sama", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                java.sql.Statement stat;
                stat = koneksi.createStatement();
                ResultSet data = stat.executeQuery("SELECT * FROM tb_akun  WHERE username ='" + jTUsername.getText() + "'");
                if (data.next()) {
                    JOptionPane.showMessageDialog(null, "Username Sudah Terdaftar", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
                    jTUsername.requestFocus();
                } else {
                    String sql = "INSERT INTO tb_akun VALUES('" + jTUsername.getText() + "'"
                            + ",'" + jPPassword.getText() + "')";                    
                    stat.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Buat Akun Berhasil", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
                    ClearData();
                }
                stat.close();
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Error : " +e, "Buat Akun", JOptionPane.WARNING_MESSAGE);
            }
        }  
    }//GEN-LAST:event_jBDaftarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buat_Akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buat_Akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buat_Akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buat_Akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buat_Akun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBack;
    private javax.swing.JButton jBDaftar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPConfir;
    private javax.swing.JPasswordField jPPassword;
    private javax.swing.JTextField jTUsername;
    // End of variables declaration//GEN-END:variables
    
     private void ClearData (){
        jTUsername.setText("");
        jPPassword.setText("");
        jPConfir.setText("");
    }
}
