/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TR_LDKM;

/**
 *
 * @author : Jean Sontri Ananta (672018266); Devylia Todingbua (672018284); Rufina Rahma Ajeng Setyaningsih (672018289)
 */

public class Home extends javax.swing.JFrame {
    
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBAdmin = new javax.swing.JButton();
        jBUser = new javax.swing.JButton();
        jBListPeserta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(460, 370));
        setMinimumSize(new java.awt.Dimension(460, 370));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBAdmin.setBackground(new java.awt.Color(255, 255, 255));
        jBAdmin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Admin.png"))); // NOI18N
        jBAdmin.setText(" ADMIN");
        jBAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdminActionPerformed(evt);
            }
        });
        getContentPane().add(jBAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, 80));

        jBUser.setBackground(new java.awt.Color(255, 255, 255));
        jBUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/User.png"))); // NOI18N
        jBUser.setText(" USER");
        jBUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUserActionPerformed(evt);
            }
        });
        getContentPane().add(jBUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 200, 80));

        jBListPeserta.setBackground(new java.awt.Color(255, 255, 255));
        jBListPeserta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBListPeserta.setText("LIST PESERTA LDKM");
        jBListPeserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListPesertaActionPerformed(evt);
            }
        });
        getContentPane().add(jBListPeserta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 400, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Latihan Dasar Kepemimpinan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Mahasiswa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/FTI.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 116, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/UKSW.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 107, -1, 109));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/LKF FTI.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 107, -1, 109));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/HomeBg.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdminActionPerformed
        Login_Admin pindah = new Login_Admin();
        pindah.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jBAdminActionPerformed

    private void jBUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUserActionPerformed
        Menu_User pindah = new Menu_User();
        pindah.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jBUserActionPerformed

    private void jBListPesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListPesertaActionPerformed
        Daftar_Peserta pindah = new Daftar_Peserta();
        pindah.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jBListPesertaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdmin;
    private javax.swing.JButton jBListPeserta;
    private javax.swing.JButton jBUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
