/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TR_LDKM;

/**
 *
 * @author : Jean Sontri Ananta (672018266); Devylia Todingbua (672018284); Rufina Rahma Ajeng Setyaningsih (672018289)
 */

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class Menu_User extends javax.swing.JFrame {
    DBConnection konn = new DBConnection();
    Connection koneksi = konn.getConn();
    
    public Menu_User() {
        initComponents();
        EditableF();
        Jumlah();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGTahun = new javax.swing.ButtonGroup();
        bGGender = new javax.swing.ButtonGroup();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jBHome = new javax.swing.JButton();
        jTJmlhPendaftar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCKTMAsli = new javax.swing.JCheckBox();
        jCFcKTM = new javax.swing.JCheckBox();
        jCFcKST = new javax.swing.JCheckBox();
        jCFoto = new javax.swing.JCheckBox();
        jBLengkap = new javax.swing.JButton();
        jTPenyakit = new javax.swing.JTextField();
        jTNoHP = new javax.swing.JTextField();
        rBPerempuan = new javax.swing.JRadioButton();
        rBLelaki = new javax.swing.JRadioButton();
        jTNama = new javax.swing.JTextField();
        jTNIM = new javax.swing.JTextField();
        jBDaftar = new javax.swing.JButton();
        jBRefresh = new javax.swing.JButton();
        jBListPeserta = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        bGTahun.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Tahun 3++ ");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        bGTahun.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Tahun 2");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        bGTahun.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Tahun 1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(660, 300));
        setMinimumSize(new java.awt.Dimension(660, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBHome.setBackground(new java.awt.Color(255, 255, 255));
        jBHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Home.png"))); // NOI18N
        jBHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHomeActionPerformed(evt);
            }
        });
        getContentPane().add(jBHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 50, 40));

        jTJmlhPendaftar.setEditable(false);
        jTJmlhPendaftar.setBackground(new java.awt.Color(255, 255, 255));
        jTJmlhPendaftar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTJmlhPendaftar.setForeground(new java.awt.Color(255, 0, 0));
        jTJmlhPendaftar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTJmlhPendaftar.setText("999 PESERTA");
        jTJmlhPendaftar.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jTJmlhPendaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTJmlhPendaftarActionPerformed(evt);
            }
        });
        getContentPane().add(jTJmlhPendaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 210, 30));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Persyaratan :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 20));

        jCKTMAsli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCKTMAsli.setForeground(new java.awt.Color(255, 255, 255));
        jCKTMAsli.setText("KTM Asli");
        jCKTMAsli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCKTMAsliActionPerformed(evt);
            }
        });
        getContentPane().add(jCKTMAsli, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 103, -1));

        jCFcKTM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCFcKTM.setForeground(new java.awt.Color(255, 255, 255));
        jCFcKTM.setText("Fc KTM");
        jCFcKTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCFcKTMActionPerformed(evt);
            }
        });
        getContentPane().add(jCFcKTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 103, -1));

        jCFcKST.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCFcKST.setForeground(new java.awt.Color(255, 255, 255));
        jCFcKST.setText("Fc KST");
        jCFcKST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCFcKSTActionPerformed(evt);
            }
        });
        getContentPane().add(jCFcKST, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 103, -1));

        jCFoto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCFoto.setForeground(new java.awt.Color(255, 255, 255));
        jCFoto.setText("Foto 3x4 (2)");
        jCFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCFotoActionPerformed(evt);
            }
        });
        getContentPane().add(jCFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jBLengkap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBLengkap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Ceklist.png"))); // NOI18N
        jBLengkap.setText(" Lengkap");
        jBLengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLengkapActionPerformed(evt);
            }
        });
        getContentPane().add(jBLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 232, 120, -1));
        getContentPane().add(jTPenyakit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 200, -1));
        getContentPane().add(jTNoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 200, -1));

        bGGender.add(rBPerempuan);
        rBPerempuan.setForeground(new java.awt.Color(255, 255, 255));
        rBPerempuan.setText("Perempuan");
        rBPerempuan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rBPerempuanItemStateChanged(evt);
            }
        });
        getContentPane().add(rBPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, 30));

        bGGender.add(rBLelaki);
        rBLelaki.setForeground(new java.awt.Color(255, 255, 255));
        rBLelaki.setText("Laki-Laki");
        rBLelaki.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rBLelakiItemStateChanged(evt);
            }
        });
        rBLelaki.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                rBLelakiComponentHidden(evt);
            }
        });
        getContentPane().add(rBLelaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 81, 30));
        getContentPane().add(jTNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 200, -1));
        getContentPane().add(jTNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 200, -1));

        jBDaftar.setBackground(new java.awt.Color(255, 255, 255));
        jBDaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/Adds.png"))); // NOI18N
        jBDaftar.setText(" Daftar");
        jBDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDaftarActionPerformed(evt);
            }
        });
        getContentPane().add(jBDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, 30));

        jBRefresh.setBackground(new java.awt.Color(255, 255, 255));
        jBRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/RefreshK.png"))); // NOI18N
        jBRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(jBRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 240, 40, 30));

        jBListPeserta.setBackground(new java.awt.Color(255, 255, 255));
        jBListPeserta.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBListPeserta.setText("LIST PESERTA");
        jBListPeserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListPesertaActionPerformed(evt);
            }
        });
        getContentPane().add(jBListPeserta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 110, 30));

        jLabel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("DAta Peserta");
        getContentPane().add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NIM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 83, 100, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 113, 100, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jenis Kelamin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 143, 100, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No. HP");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 173, 100, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Penyakit");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 203, 100, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/MenuUser.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCKTMAsliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCKTMAsliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCKTMAsliActionPerformed

    private void jCFcKTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCFcKTMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCFcKTMActionPerformed

    private void jCFcKSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCFcKSTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCFcKSTActionPerformed

    private void jCFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCFotoActionPerformed

    private void rBPerempuanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rBPerempuanItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rBPerempuanItemStateChanged

    private void rBLelakiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rBLelakiItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rBLelakiItemStateChanged

    private void rBLelakiComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_rBLelakiComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_rBLelakiComponentHidden

    private void jBDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDaftarActionPerformed
        String JK = null;
        if (rBLelaki.isSelected()) {
            JK = "Laki-Laki";
        } if (rBPerempuan.isSelected()) {
            JK = "Perempuan";
        }

        if (jTNama.getText().trim().equals("")
            || jTNIM.getText().trim().equals("")
            || JK == null
            || jTNoHP.getText().trim().equals("")
            || jTPenyakit.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Data Tidak Lengkap", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Statement Stat;
                Stat = koneksi.createStatement();
                ResultSet data = Stat.executeQuery("SELECT * FROM tb_peserta WHERE NIM ='" + jTNIM.getText() + "'");
                if (data.next()) {
                    JOptionPane.showMessageDialog(null, "NIM Sudah Terdaftar", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
                    jTNIM.requestFocus();
                } else {
                    String sql = "INSERT INTO tb_peserta VALUES('" + jTNIM.getText() + "'"
                    + ",'" + jTNama.getText() + "'"
                    + ",'" + JK + "'"
                    + ",'" + jTNoHP.getText()+ "'"
                    + ",'" + jTPenyakit.getText() + "')";
                    Stat.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Pendaftaran Berhasil", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
                    ClearData();
                    EditableF();
                    Jumlah();
                }
                Stat.close();
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, "Error : " +e, "Save", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBDaftarActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jBLengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLengkapActionPerformed
        if (jCKTMAsli.isSelected() && jCFcKTM.isSelected() && jCFcKST.isSelected() && jCFoto.isSelected()){
            jTNIM.setEditable(true);
            jTNama.setEditable(true);
            jTNoHP.setEditable(true);
            jTPenyakit.setEditable(true);
            rBLelaki.setEnabled(true);
            rBPerempuan.setEnabled(true);
            jBDaftar.setEnabled(true);
            jBRefresh.setEnabled(true);
            jTNIM.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Persyaratan Belum Lengkap!", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBLengkapActionPerformed

    private void jBHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHomeActionPerformed
        Home pindah = new Home();
        pindah.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBHomeActionPerformed

    private void jBRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRefreshActionPerformed
        ClearData();
        EditableF();
    }//GEN-LAST:event_jBRefreshActionPerformed

    private void jBListPesertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListPesertaActionPerformed
        Daftar_Peserta pindah = new Daftar_Peserta();
        pindah.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBListPesertaActionPerformed

    private void jTJmlhPendaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTJmlhPendaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTJmlhPendaftarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGGender;
    private javax.swing.ButtonGroup bGTahun;
    private javax.swing.JButton jBDaftar;
    private javax.swing.JButton jBHome;
    private javax.swing.JButton jBLengkap;
    private javax.swing.JButton jBListPeserta;
    private javax.swing.JButton jBRefresh;
    private javax.swing.JCheckBox jCFcKST;
    private javax.swing.JCheckBox jCFcKTM;
    private javax.swing.JCheckBox jCFoto;
    private javax.swing.JCheckBox jCKTMAsli;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTJmlhPendaftar;
    public javax.swing.JTextField jTNIM;
    public javax.swing.JTextField jTNama;
    public javax.swing.JTextField jTNoHP;
    public javax.swing.JTextField jTPenyakit;
    public javax.swing.JRadioButton rBLelaki;
    public javax.swing.JRadioButton rBPerempuan;
    // End of variables declaration//GEN-END:variables
    
    private void EditableF(){
        jTNIM.setEditable(false);
        jTNama.setEditable(false);
        jTNoHP.setEditable(false);
        jTPenyakit.setEditable(false);    
        rBLelaki.setEnabled(false);
        rBPerempuan.setEnabled(false);
        jBDaftar.setEnabled(false);
        jBRefresh.setEnabled(false);
    }
    
    private void ClearData(){
        jTNama.setText("");
        jTNIM.setText("");
        jTNoHP.setText("");
        jTPenyakit.setText("");
        jCKTMAsli.setSelected(false);
        jCFcKTM.setSelected(false);
        jCFcKST.setSelected(false);
        jCFoto.setSelected(false);
        bGGender.clearSelection();
    }

    private void Jumlah() {
        Daftar_Peserta daf = new Daftar_Peserta();
        int jmlh = daf.jTDaftarPeserta.getRowCount();
        jTJmlhPendaftar.setText(""+jmlh+" PESERTA");
    }
}
